name: dates_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  tflite_flutter: ^0.11.0
  image: ^3.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # Check for the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - "assets/best_model.tflite"
  uses-material-design: true
